version: '2' 
services:
 namenode:
    image: bde2020/hadoop-namenode:1.0.0
    hostname: namenode
    container_name: namenode
    domainname: hadoop
    networks:
      - hadoop
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - INIT_DAEMON_STEP=setup_hdfs
      - VIRTUAL_HOST=hdfs.demo.big-data-europe.local
    env_file:
      - ./config/hadoop/hadoop.env
    ports:
      - "50070:50070"
      - "8020:8020"
 datanode1:
    image: bde2020/hadoop-datanode:1.0.0
    hostname: datanode1
    container_name: datanode1
    domainname: hadoop
    networks:
      - hadoop
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    env_file:
      - ./config/hadoop/hadoop.env

 datanode2:
    image: bde2020/hadoop-datanode:1.0.0
    hostname: datanode2
    container_name: datanode2
    domainname: hadoop
    networks: 
      - hadoop
    volumes:
      - ./data/datanode2:/hadoop/dfs/data
    env_file:
      - ./config/hadoop/hadoop.env

 flink-master:
   image: bde2020/flink-master
   hostname: flink-master
   container_name: flink-master
   domainname: hadoop
   networks:
     - hadoop
   environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - INIT_DAEMON_STEP=setup_flink
      - VIRTUAL_HOST=flink-master.demo.big-data-europe.local
      - VIRTUAL_PORT=8080
   env_file:
      - ./config/hadoop/hadoop.env
   ports:
     - "8080:8080"
     - "8081:8081"

 flink-worker:
   image: bde2020/flink-worker
   hostname: flink-worker
   container_name: flink-worker
   domainname: hadoop
   networks: 
     - hadoop
   environment:
     - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
     - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
     - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
     - VIRTUAL_HOST=flink-worker.demo.big-data-europe.local
     -  VIRTUAL_PORT=8081 
   env_file:
     - ./config/hadoop/hadoop.env
   links:
      - "flink-master"

 flink-starter:
    build: .
    environment:
      -INIT_DAEMON_STEP=compute_aggregations
      -HDFS_URL=hdfs://namenode:8020
    links:
      - "master:flink-master"

 integratorui:
    image: bde2020/integrator-ui:latest
    volumes:
      - ./config/integrator:/app/config
    environment:
      VIRTUAL_HOST: flink-starter.big-data-europe.local
 hue:
    image: bde2020/hdfs-filebrowser:3.9
    hostname: hdfsfb
    container_name: hdfsfb
    domainname: hadoop
    networks:
      - hadoop
    environment:
      - NAMENODE_HOST=namenode
      - VIRTUAL_HOST=hue.demo.big-data-europe.local
      - VIRTUAL_PORT=8088
    ports:
      - "8088:8088"

networks:
  hadoop:
    external: true
