 namenode:
    image: bde2020/hadoop-namenode:1.0.0
    hostname: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./config/hadoop/hadoop.env
    ports:
      - "50070:50070"
      - "8020:8020"

 datanode1:
    image: bde2020/hadoop-datanode:1.0.0
    hostname: datanode1
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    env_file:
      - ./config/hadoop/hadoop.env
    links:
      - "namenode:namenode"

 datanode2:
    image: bde2020/hadoop-datanode:1.0.0
    volumes:
      - ./data/datanode2:/hadoop/dfs/data
    env_file:
      - ./config/hadoop/hadoop.env
    links:
      - "namenode:namenode"
 flinkmaster:
    image: bde2020/flink-master:latest
    hostname: flink-master
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    env_file:
      - ./config/hadoop/hadoop.env
    ports:
        - "8080:8080"
        - "8081:8081"
 flinkworker:
    image: bde2020/flink-worker:latest
    hostname: flink-worker
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    env_file:
      - ./config/hadoop/hadoop.env
    links:
      - "flinkmaster:flink-master"
 hue:
    image: bde2020/hdfs-filebrowser:3.9
    hostname: hdfsfb
    environment:
      - NAMENODE_HOST=namenode
    ports:
      - "8088:8088"
